[project]
name = "app_template"
version = "0.1.0"
description = "Python app scaffolded from templates"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "python-dotenv",
    "pytest"
]

[tool.uv]
python = "3.11"
